[[plugins]]
  package = "netlify-plugin-cloudinary"
  
  [plugins.inputs]
    cloudName = "duym3yaqb"
    deliveryType = "upload"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

[[plugins]]
  package = "netlify-plugin-minify-html"
  
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
  
  [plugins.inputs.minifierOptions]
    removeComments = false
    collapseInlineTagWhitespace = false

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
  
  [plugins.inputs]
    fileFilter = ["*.html"]
    directoryFilter = ["!node_modules"]
    extract = false
    dimensions = [
      { width = 414, height = 896 },
      { width = 1920, height = 1080 }
    ]

[[plugins]]
  package = "netlify-plugin-debug-cache"
